version: "3.6" 
services:
  work:
    build: .
    environment:
      - MINIDLNA_media_dir=V,/media
      - MINIDLNA_friendly_name=Movies
    volumes: 
      - type: bind
        source: /home/sego/tst
        target: /media
        read_only: true
      - type: bind
        source: /home/sego/tst_db
        target: /db
    ports:
      - 8200:8200
      - 1901:1900/udp
