version: "3.6" 
services:
  work:
    privileged: true
    build: .
    environment: 
      - MINIDLNA_media_dir=V,/media
      - MINIDLNA_friendly_name=Movies
  sut:
    image: alpine
    depends_on:
      - work
    command: >
      /bin/sh -c "
        sleep 15;
        wget work:8200;
      "
